"""SQLite helpers for the Prototype tab (puzzles generated by the NHM simulator, reviewed
and edited by staff, optionally tested on one model).

Kept in its own database file, separate from narc.db and narrate.db (Bert, September 28,
2026: "any prototyping should be part of a separate db from the others we currently have,
including on prod"):
  - nothing here is a benchmark puzzle or a human-subject record;
  - runs are generated in bulk and thrown away; they must not ride along with narc.db
    syncs, merges and dataset exports;
  - a prototype that graduates is exported as JSON and submitted through the normal path.

Path: env PROTO_DB_PATH (default proto_data/proto.db). In docker-compose the proto_data/
directory is bind-mounted so the WAL files live on the host.
"""

import json
import os
import sqlite3
from pathlib import Path

DB_PATH = os.environ.get("PROTO_DB_PATH", "proto_data/proto.db")

SCHEMA = """
CREATE TABLE IF NOT EXISTS runs (
    run_id        INTEGER PRIMARY KEY AUTOINCREMENT,
    name          TEXT NOT NULL,
    config_json   TEXT NOT NULL,             -- the knobs: grammar, phi, sym, mask, n, seed, m, ...
    summary_json  TEXT,                      -- yield, rejection reasons, depth / event distributions
    nhm_version   TEXT,                      -- nhmsim generator version
    created_by    TEXT,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS puzzles (
    puzzle_id     TEXT PRIMARY KEY,
    run_id        INTEGER NOT NULL REFERENCES runs(run_id) ON DELETE CASCADE,
    puzzle_json   TEXT NOT NULL,             -- narc-format JSON incl. metadata.events (the editable chain)
    verdict       TEXT NOT NULL DEFAULT '',  -- '' | keep | fix | drop
    notes         TEXT NOT NULL DEFAULT '',
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_proto_puzzles_run ON puzzles(run_id);

-- One row per (puzzle, model, narrative surface, condition) trial, run through the
-- benchmark's own collect.run_trial (same prompts, two-pass protocol, parser, grader).
CREATE TABLE IF NOT EXISTS trials (
    trial_id         INTEGER PRIMARY KEY AUTOINCREMENT,
    puzzle_id        TEXT NOT NULL REFERENCES puzzles(puzzle_id) ON DELETE CASCADE,
    model_name       TEXT NOT NULL,
    surface          TEXT NOT NULL,          -- story | grammar | design | physical | terse | ...
    condition        TEXT NOT NULL,          -- grids_only | narrative_only | both
    narrative        TEXT,                   -- snapshot of the text used (None for grids_only)
    status           TEXT NOT NULL DEFAULT 'queued'
                     CHECK(status IN ('queued', 'running', 'done', 'failed')),
    raw_response     TEXT,
    response_text    TEXT,
    reasoning        TEXT,
    predicted_grids  TEXT,                   -- JSON
    correct          INTEGER,
    cell_accuracy    REAL,
    error            TEXT,
    latency_ms       INTEGER,
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    response_at      TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_proto_trials_puzzle ON trials(puzzle_id);
"""


def init_db(path=None):
    path = path or DB_PATH
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(path, timeout=30)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    conn.executescript(SCHEMA)
    return conn


# --- runs ---

def insert_run(conn, name, config, summary, nhm_version, created_by):
    cur = conn.execute(
        "INSERT INTO runs (name, config_json, summary_json, nhm_version, created_by) VALUES (?, ?, ?, ?, ?)",
        (name, json.dumps(config), json.dumps(summary), nhm_version, created_by))
    conn.commit()
    return cur.lastrowid


def get_runs(conn):
    rows = conn.execute(
        "SELECT r.*, (SELECT COUNT(*) FROM puzzles p WHERE p.run_id = r.run_id) AS n_puzzles, "
        "(SELECT COUNT(*) FROM puzzles p WHERE p.run_id = r.run_id AND p.verdict = 'keep') AS n_keep, "
        "(SELECT COUNT(*) FROM puzzles p WHERE p.run_id = r.run_id AND p.verdict = 'drop') AS n_drop "
        "FROM runs r ORDER BY r.run_id DESC").fetchall()
    return [dict(r) for r in rows]


def get_run(conn, run_id):
    r = conn.execute("SELECT * FROM runs WHERE run_id = ?", (run_id,)).fetchone()
    return dict(r) if r else None


def delete_run(conn, run_id):
    conn.execute("DELETE FROM runs WHERE run_id = ?", (run_id,))
    conn.commit()


# --- puzzles ---

def insert_puzzle(conn, run_id, puzzle):
    conn.execute("INSERT OR REPLACE INTO puzzles (puzzle_id, run_id, puzzle_json) VALUES (?, ?, ?)",
                 (puzzle["puzzle_id"], run_id, json.dumps(puzzle)))


def get_puzzles(conn, run_id, verdict=None):
    sql = "SELECT * FROM puzzles WHERE run_id = ?"
    args = [run_id]
    if verdict is not None:
        sql += " AND verdict = ?"
        args.append(verdict)
    sql += " ORDER BY puzzle_id"
    return [dict(r) for r in conn.execute(sql, args).fetchall()]


def get_puzzle(conn, puzzle_id):
    r = conn.execute("SELECT * FROM puzzles WHERE puzzle_id = ?", (puzzle_id,)).fetchone()
    return dict(r) if r else None


def update_puzzle_json(conn, puzzle_id, puzzle):
    conn.execute("UPDATE puzzles SET puzzle_json = ?, updated_at = CURRENT_TIMESTAMP WHERE puzzle_id = ?",
                 (json.dumps(puzzle), puzzle_id))
    conn.commit()


def update_review(conn, puzzle_id, verdict=None, notes=None):
    sets, args = [], []
    if verdict is not None:
        sets.append("verdict = ?")
        args.append(verdict)
    if notes is not None:
        sets.append("notes = ?")
        args.append(notes)
    if not sets:
        return
    sets.append("updated_at = CURRENT_TIMESTAMP")
    args.append(puzzle_id)
    conn.execute(f"UPDATE puzzles SET {', '.join(sets)} WHERE puzzle_id = ?", args)
    conn.commit()


def delete_puzzle(conn, puzzle_id):
    conn.execute("DELETE FROM puzzles WHERE puzzle_id = ?", (puzzle_id,))
    conn.commit()


# --- trials ---

def insert_trial(conn, puzzle_id, model_name, surface, condition, narrative):
    cur = conn.execute(
        "INSERT INTO trials (puzzle_id, model_name, surface, condition, narrative) VALUES (?, ?, ?, ?, ?)",
        (puzzle_id, model_name, surface, condition, narrative))
    conn.commit()
    return cur.lastrowid


def set_trial_status(conn, trial_id, status):
    conn.execute("UPDATE trials SET status = ? WHERE trial_id = ?", (status, trial_id))
    conn.commit()


def finish_trial(conn, trial_id, raw_response, response_text, reasoning, predicted, correct, cell_accuracy,
                 error, latency_ms):
    conn.execute(
        "UPDATE trials SET status = ?, raw_response = ?, response_text = ?, reasoning = ?, predicted_grids = ?, "
        "correct = ?, cell_accuracy = ?, error = ?, latency_ms = ?, response_at = CURRENT_TIMESTAMP WHERE trial_id = ?",
        ("failed" if error else "done", raw_response, response_text, reasoning,
         json.dumps(predicted) if predicted is not None else None, correct, cell_accuracy, error, latency_ms, trial_id))
    conn.commit()


def get_trials(conn, puzzle_id):
    return [dict(r) for r in conn.execute(
        "SELECT * FROM trials WHERE puzzle_id = ? ORDER BY trial_id", (puzzle_id,)).fetchall()]


def verdicts_by_cell(trials):
    """(model, surface) -> {grids_only, narrative_only, both, narc} from finished trials."""
    cells = {}
    for t in trials:
        if t["status"] != "done":
            continue
        key = (t["model_name"], t["surface"])
        cells.setdefault(key, {})[t["condition"]] = t["correct"]
    out = {}
    for key, c in cells.items():
        if all(k in c for k in ("grids_only", "narrative_only", "both")):
            c["narc"] = int(c["both"] == 1 and c["grids_only"] == 0 and c["narrative_only"] == 0)
        out[key] = c
    return out
